// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/server/epic_storage.go
//
// Generated by this command:
//
//	mockgen -source=./internal/storage/server/epic_storage.go -destination ./internal/service/server/mock_epic_storage_test.go -package server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	model "github.com/Stern-Ritter/gophertask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockEpicStorage is a mock of EpicStorage interface.
type MockEpicStorage struct {
	ctrl     *gomock.Controller
	recorder *MockEpicStorageMockRecorder
}

// MockEpicStorageMockRecorder is the mock recorder for MockEpicStorage.
type MockEpicStorageMockRecorder struct {
	mock *MockEpicStorage
}

// NewMockEpicStorage creates a new mock instance.
func NewMockEpicStorage(ctrl *gomock.Controller) *MockEpicStorage {
	mock := &MockEpicStorage{ctrl: ctrl}
	mock.recorder = &MockEpicStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEpicStorage) EXPECT() *MockEpicStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEpicStorage) Create(ctx context.Context, epic model.Epic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, epic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEpicStorageMockRecorder) Create(ctx, epic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEpicStorage)(nil).Create), ctx, epic)
}

// Delete mocks base method.
func (m *MockEpicStorage) Delete(ctx context.Context, epicID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, epicID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEpicStorageMockRecorder) Delete(ctx, epicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEpicStorage)(nil).Delete), ctx, epicID)
}

// GetAll mocks base method.
func (m *MockEpicStorage) GetAll(ctx context.Context, userID string) ([]model.Epic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].([]model.Epic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEpicStorageMockRecorder) GetAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEpicStorage)(nil).GetAll), ctx, userID)
}

// GetByID mocks base method.
func (m *MockEpicStorage) GetByID(ctx context.Context, epicID string) (model.Epic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, epicID)
	ret0, _ := ret[0].(model.Epic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEpicStorageMockRecorder) GetByID(ctx, epicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEpicStorage)(nil).GetByID), ctx, epicID)
}

// Update mocks base method.
func (m *MockEpicStorage) Update(ctx context.Context, epic model.Epic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, epic)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEpicStorageMockRecorder) Update(ctx, epic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEpicStorage)(nil).Update), ctx, epic)
}
